services:
  ubuntu-texlive-ja:
    build: .
    command: sleep infinity

    volumes:
      - ../:/workdir
      - ${HOME}/.gitconfig:/root/.gitconfig:ro
      - ./.latexmkrc:/root/.latexmkrc

    environment:
      LANG: "ja_JP.UTF-8"
      TZ: "Asia/Tokyo"
